sudo: required

language: generic
services :
  - docker

before_install: 
  - echo "start creating an image"
  - docker build -t wang/docker-react-app -f Dockerfile.dev .

script: 
  - docker run -e CI=true wang/docker-react-app npm run test -- --coverage

after_success: 
  - echo "test success"

